// <auto-generated />
using Frontend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Frontend.Data.Migrations
{
    [DbContext(typeof(SpotifyDbContext))]
    partial class SpotifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Frontend.Data.Models.Album", b =>
                {
                    b.Property<string>("AlbumUri")
                        .HasColumnType("TEXT")
                        .HasColumnName("albumUri");

                    b.Property<string>("AlbumCoverUri")
                        .HasColumnType("TEXT")
                        .HasColumnName("albumCoverUri");

                    b.Property<string>("AlbumName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("albumName");

                    b.Property<string>("ArtistName")
                        .HasColumnType("TEXT")
                        .HasColumnName("artistName");

                    b.HasKey("AlbumUri");

                    b.HasIndex("ArtistName");

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("Frontend.Data.Models.AlbumImage", b =>
                {
                    b.Property<string>("AlbumUri")
                        .HasColumnType("TEXT")
                        .HasColumnName("albumUri");

                    b.Property<byte[]>("ImageBlob")
                        .HasColumnType("BLOB")
                        .HasColumnName("imageBlob");

                    b.HasKey("AlbumUri");

                    b.ToTable("albumImage", (string)null);
                });

            modelBuilder.Entity("Frontend.Data.Models.Marquee", b =>
                {
                    b.Property<string>("ArtistName")
                        .HasColumnType("TEXT")
                        .HasColumnName("artistName");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.HasKey("ArtistName");

                    b.ToTable("marquee", (string)null);
                });

            modelBuilder.Entity("Frontend.Data.Models.PodcastShow", b =>
                {
                    b.Property<string>("ShowName")
                        .HasColumnType("TEXT")
                        .HasColumnName("showName");

                    b.Property<long>("MsPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("msPlayed");

                    b.HasKey("ShowName");

                    b.ToTable("podcastShows", (string)null);
                });

            modelBuilder.Entity("Frontend.Data.Models.StreamingHistoryMusic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AlbumName")
                        .HasColumnType("TEXT")
                        .HasColumnName("albumName");

                    b.Property<string>("ArtistName")
                        .HasColumnType("TEXT")
                        .HasColumnName("artistName");

                    b.Property<long>("MsPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("msPlayed");

                    b.Property<int>("Offline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("offline");

                    b.Property<string>("ReasonEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("reasonEnd");

                    b.Property<string>("ReasonStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("reasonStart");

                    b.Property<int>("Shuffled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("shuffled");

                    b.Property<int>("Skipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("skipped");

                    b.Property<string>("TrackName")
                        .HasColumnType("TEXT")
                        .HasColumnName("trackName");

                    b.Property<string>("TrackUri")
                        .HasColumnType("TEXT")
                        .HasColumnName("trackUri");

                    b.Property<long>("Ts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.HasIndex("ArtistName")
                        .HasDatabaseName("idxMusicHistoryArtist");

                    b.HasIndex("TrackUri")
                        .HasDatabaseName("idxMusicHistoryTrack");

                    b.HasIndex("Ts")
                        .HasDatabaseName("idxMusicHistoryTs");

                    b.ToTable("streamingHistoryMusic", (string)null);
                });

            modelBuilder.Entity("Frontend.Data.Models.StreamingHistoryPodcast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("EpisodeName")
                        .HasColumnType("TEXT")
                        .HasColumnName("episodeName");

                    b.Property<string>("EpisodeUri")
                        .HasColumnType("TEXT")
                        .HasColumnName("episodeUri");

                    b.Property<long>("MsPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("msPlayed");

                    b.Property<string>("ShowName")
                        .HasColumnType("TEXT")
                        .HasColumnName("showName");

                    b.Property<long>("Ts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ts");

                    b.HasKey("Id");

                    b.HasIndex("ShowName")
                        .HasDatabaseName("idxPodcastHistoryShow");

                    b.HasIndex("Ts")
                        .HasDatabaseName("idxPodcastHistoryTs");

                    b.ToTable("streamingHistoryPodcast", (string)null);
                });

            modelBuilder.Entity("Frontend.Data.Models.Track", b =>
                {
                    b.Property<string>("TrackUri")
                        .HasColumnType("TEXT")
                        .HasColumnName("trackUri");

                    b.Property<string>("AlbumUri")
                        .HasColumnType("TEXT")
                        .HasColumnName("albumUri");

                    b.Property<string>("ArtistName")
                        .HasColumnType("TEXT")
                        .HasColumnName("artistName");

                    b.Property<long>("MsPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("msPlayed");

                    b.Property<int>("Shuffled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("shuffled");

                    b.Property<int>("Skipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("skipped");

                    b.Property<string>("TrackName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("trackName");

                    b.HasKey("TrackUri");

                    b.HasIndex("AlbumUri");

                    b.HasIndex("ArtistName");

                    b.ToTable("tracks", (string)null);
                });

            modelBuilder.Entity("Frontend.Data.Models.Album", b =>
                {
                    b.HasOne("Frontend.Data.Models.Marquee", "Artist")
                        .WithMany("Albums")
                        .HasForeignKey("ArtistName");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Frontend.Data.Models.AlbumImage", b =>
                {
                    b.HasOne("Frontend.Data.Models.Album", "Album")
                        .WithOne("AlbumImage")
                        .HasForeignKey("Frontend.Data.Models.AlbumImage", "AlbumUri")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Frontend.Data.Models.StreamingHistoryMusic", b =>
                {
                    b.HasOne("Frontend.Data.Models.Marquee", "Artist")
                        .WithMany("StreamingHistory")
                        .HasForeignKey("ArtistName");

                    b.HasOne("Frontend.Data.Models.Track", "Track")
                        .WithMany("StreamingHistory")
                        .HasForeignKey("TrackUri");

                    b.Navigation("Artist");

                    b.Navigation("Track");
                });

            modelBuilder.Entity("Frontend.Data.Models.StreamingHistoryPodcast", b =>
                {
                    b.HasOne("Frontend.Data.Models.PodcastShow", "Show")
                        .WithMany("StreamingHistory")
                        .HasForeignKey("ShowName");

                    b.Navigation("Show");
                });

            modelBuilder.Entity("Frontend.Data.Models.Track", b =>
                {
                    b.HasOne("Frontend.Data.Models.Album", "Album")
                        .WithMany("Tracks")
                        .HasForeignKey("AlbumUri");

                    b.HasOne("Frontend.Data.Models.Marquee", "Artist")
                        .WithMany("Tracks")
                        .HasForeignKey("ArtistName");

                    b.Navigation("Album");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Frontend.Data.Models.Album", b =>
                {
                    b.Navigation("AlbumImage");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Frontend.Data.Models.Marquee", b =>
                {
                    b.Navigation("Albums");

                    b.Navigation("StreamingHistory");

                    b.Navigation("Tracks");
                });

            modelBuilder.Entity("Frontend.Data.Models.PodcastShow", b =>
                {
                    b.Navigation("StreamingHistory");
                });

            modelBuilder.Entity("Frontend.Data.Models.Track", b =>
                {
                    b.Navigation("StreamingHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
